name: Notify Parent Repo

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to parent repo
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            axios.post('https://api.github.com/repos/CodeWithDhruvX/go-projects/dispatches', {
              event_type: 'child_repo_update', // Custom event name
            }, {
              headers: {
                'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
                'Accept': 'application/vnd.github.v3+json'
              }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
