name: Update Parent Repository
on:
  push:
    branches:
      - main

jobs:
  update_parent_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Clone Parent Repository with Submodules
        run: |
          git clone --recurse-submodules https://github.com/CodeWithDhruvX/go-projects.git
          cd go-projects

          # Ensure submodule uses HTTPS
          git config submodule.golang-http-server.url https://github.com/CodeWithDhruvX/golang-http-server.git

          # Update the submodule
          git submodule update --remote golang-http-server

          # Stage and commit submodule changes
          git add golang-http-server
          git commit -m "Update submodule: golang-http-server to latest commit"

          # Set up authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CodeWithDhruvX/go-projects.git

          # Push changes to the parent repository
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
