name: Update Parent Repository
on:
  push:
    branches:
      - main  # or relevant branch for your child repo

jobs:
  update_parent_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Child Repository
        uses: actions/checkout@v2

      # (Optional) Add any build or test steps for the child repository
      - name: Build Child Repository
        run: |
          echo "Building child repository..."
          # Add your build steps here (if any)

      - name: Commit and Push Changes to Parent Repository
        run: |
          # Clone the parent repository
          git clone https://github.com/CodeWithDhruvX/go-projects.git
          cd go-projects
          
          # Update the submodule
          git submodule update --remote  # Updates the child repo reference in the parent repo
          
          # Stage the submodule changes and commit
          git add golang-http-server  # Use the actual submodule path from .gitmodules
          git commit -m "Updated child repository submodule"
          
          # Push changes to the parent repository
          git push origin main  # Or the relevant branch for the parent repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
